### PR TITLE
center clock

### PR DESCRIPTION
**Pull request by ZsuzsaMano**
Please check. For me, it looks centered now.

### CODE REVIEW

**Comment by vishnuramana** [comment]
Let me take a look and get back.

**Comment by ZsuzsaMano** [comment]
Sure. Just let me know if you need any other adjustments. I love CSS.

**Comment by vishnuramana** [comment]
I took a look at the clock and I could find a couple of things

- The second hand doesn't extend to the border of the clock like the original.
- At 50px, the hour and minute hands are still bigger in size compared to the second hand.
- In Chrome, the minute and second hands do small movements on every second. In Firefox, it doesn't happen.

**Comment by ZsuzsaMano** [comment]
I just wanted to center it first, as that was the main issue but I can check also the other issues. 
Is it important that the second-hand extends to the border? I mean on none of the real clocks does, so it kind of disturbed my eyes.

**Comment by vishnuramana** [comment]
Sure. I think the centering issue is now fixed.

> Is it important that the second-hand extends to the border? 

Yes, since the size of the minute hand is very closer to the size of the second hand, it would be clearer to have the second hand touching the border.

**Comment by ZsuzsaMano** [comment]
I think it would help if you would describe exectly what you would like to have. I am watching my clock on the wall and trying to adjust it, so it looks similar. 
For example, the second hand is normally much thinner than the other ones, but I can make it thicker if you like.

**Comment by ZsuzsaMano** [comment]
In chrome, I don't see a small movement. Anyway. I didn't touch js or animation/transition. 
If you are still noticing it, maybe open a new issue on it.

**Comment by vishnuramana** [comment]
> I think it would help if you would describe exectly what you would like to have. I am watching my clock on the wall and trying to adjust it, so it looks similar.
> For example, the second hand is normally much thinner than the other ones, but I can make it thicker if you like.

Hey, the css issues are already explained in the Issues. Kindly read it again to understand it better. 

The first issue states that the clock hands and center size are not relative to the size of the base size. That means that whenever you change the base size of the clock, the size (thickness only) of the hands also reduce and increase. But you also have to have a min and max width property set so that the hands don't become too thin beyond a certain size and too big beyond a certain size. The min and max thickness of the hands are up to you as long as it doesn't look awkward.  

You do not have to change the length of the hands as that is how this clock is designed. It is different from traditional clocks but that's how I would like to keep this. There are other open source clock libraries which look exactly like traditional clocks. Here, it's more of a flat design and I would like to keep it the same way. 

>In chrome, I don't see a small movement. Anyway. I didn't touch js or animation/transition.
>If you are still noticing it, maybe open a new issue on it.

Yes, I can see that you haven't changed the js or css transitions. But changing the values to % values has made that happen. Please check if there is a better way to use variable values other than using percentages. _Hint: calc()_

**Comment by ZsuzsaMano** [comment]
Could you explain how % values can make 'that' happen? I must miss some important information.

**Pull request closed without merging**
