### PR TITLE
Add prop to control centerBorderColor

### PR DESCRIPTION
**Pull request by andrewgierens**
Thanks for the awesome package!

I have added a prop to control the centerBorderColor

Let me know if there are any issues

### CODE REVIEW

**Comment by andrewgierens** [comment]
@vishnuramana

**Comment by vishnuramana** [comment]
@andrewgierens Thanks for your contribution. I was busy this weekend and couldn't get time to take a look. Please give me sometime to look into this :)

**Comment by andrewgierens** [comment]
Hey - Any chance you can review and merge this? :)

**Comment by vishnuramana** [comment]
Merged it. Thank you for the PR. Will add your name to the contributors list :+1:

**Comment by vishnuramana** [comment]
Unfortunately, my base branch was set to `master `and hence your name was not showing up in the contributors list. I changed the base branch to `dev `but still it did not show up (maybe it was counted as past contributions)

If you can, you can pick any of the issues (the ones I created) and raise a PR for the same and I will merge it correctly this time. Meanwhile, I'm also looking into how this can be done the best way.

**Comment by andrewgierens** [comment]
No worries mate - Thanks for that.

**Pull request merged**
