### PR TITLE
Hour hand fix

### PR DESCRIPTION
**Pull request by andrio12**
Correcting position of the hour hand.

The hour hand only moves on a new hour, making the clock confusing when the hour is almost up. This pull request fixes the hour hand so it moves ever so slightly towards the next hour like a real clock would.

11:55 - Orginally it looks like the clock is almost 11
clock1

11:55 - After the fix it now makes sense.
clock2

Another example:

17:50 - Orginal
clock3

17:50 - Fixed
clock4

### CODE REVIEW

**Comment by vishnuramana** [comment]
Hey @andrio12 , Thanks for the PR. I will review it over the weekend and merge it.

**Comment by vishnuramana** [comment]
Change looks good. Can you please revert the package-lock.json deletion ? 

I've also added some tests for the clock components. It would be better if you could update them as per the new angle calculations for the hour hand.

**Comment by vishnuramana** [comment]
Hi @andrio12 , can you please let me know if you can work on my comments. Your PR has some valuable changes that I would like to merge (which will also add you as a contributor to this project that I would be happy to do so). 

So let me know if you would be able to find time to make the changes. If not, please do let me know so that I can do them on my own.

**Comment by andrio12** [comment]
Hi Vishnu

Sorry, work has been crazy. I made a new PR with the changes only:
https://github.com/vishnuramana/analogclock/pull/24

Sorry again how long this took. Time just flies sometimes ;)

regards
Andri

**Comment by vishnuramana** [comment]
Hey no problem :) ! 

Thanks once again for the PR.

**Pull request closed without merging**
